#!/usr/bin/env node
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const mobile = join(root, 'apps/mobile');
const args = process.argv.slice(2);
function option(name, fallback) { const index = args.indexOf(name); return index < 0 ? fallback : args[index + 1]; }
function run(command, argv, cwd = root, capture = false, env = process.env) {
    const result = spawnSync(command, argv, { cwd, env, encoding: 'utf8', stdio: capture ? 'pipe' : 'inherit', shell: process.platform === 'win32' && /\.(bat|cmd)$/i.test(command) });
    if (result.error || result.status !== 0) throw new Error(`${command} ${argv.join(' ')} failed (${result.status}): ${result.error?.message ?? result.stderr ?? ''}`);
    return (result.stdout || '').trim();
}
const bun = process.env.BUN_BIN || (existsSync(join(root, '.tools/bun/bun-windows-x64/bun.exe')) ? join(root, '.tools/bun/bun-windows-x64/bun.exe') : 'bun');
const channel = option('--variant', 'development');
const versionCode = Number(option('--version-code', process.env.MOE_VERSION_CODE || '1'));
if (!['development', 'stable'].includes(channel)) throw new Error('Variant must be development or stable.');
if (!Number.isSafeInteger(versionCode) || versionCode < 1 || versionCode > 2100000000) throw new Error('Invalid versionCode.');
const sourceSha = run('git', ['rev-parse', 'HEAD'], root, true);
const dirty = run('git', ['status', '--porcelain', '--untracked-files=normal'], root, true) !== '';
if (channel === 'stable' && (dirty || !args.includes('--version-code'))) throw new Error('Stable requires a clean commit and explicit --version-code.');
const sdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
const pinnedBun = readFileSync(join(root, '.bun-version'), 'utf8').trim();
const actualBun = run(bun, ['--version'], root, true);
if (actualBun !== pinnedBun) throw new Error(`Bun ${pinnedBun} required, found ${actualBun}.`);
if (!sdk || !existsSync(sdk)) throw new Error('Set ANDROID_HOME to an existing SDK (platform 36, build-tools 36.0.0, NDK 27.1.12297006).');
const java = spawnSync(process.env.JAVA_HOME ? join(process.env.JAVA_HOME, 'bin', process.platform === 'win32' ? 'java.exe' : 'java') : 'java', ['-version'], { encoding: 'utf8' });
if (java.status !== 0 || !/version "(?:17|21)[.\"]/.test(java.stderr || '')) throw new Error('JDK 17 or 21 is required; configure JAVA_HOME and PATH.');
const ninjaPath = join(sdk, 'cmake/3.22.1/bin', process.platform === 'win32' ? 'ninja.exe' : 'ninja');
const ninjaVersion = existsSync(ninjaPath) ? run(ninjaPath, ['--version'], root, true) : 'Gradle-managed';
if (process.platform === 'win32' && /^1\.(?:[0-9]|10|11)\./.test(ninjaVersion)) {
    throw new Error('Windows codegen needs long-path-capable Ninja. Run scripts/moe/prepare-windows-ninja.ps1 for the project-local SDK.');
}
const report = { sourceSha, dirty, channel, versionCode, bun: actualBun, node: process.version, java: java.stderr.trim(), sdk, ninjaVersion, lockSha256: createHash('sha256').update(readFileSync(join(root, 'bun.lock'))).digest('hex') };
console.log(JSON.stringify(report, null, 2));
if (args.includes('--check')) process.exit(0);
if (!existsSync(join(root, 'node_modules'))) throw new Error('Run bun install --frozen-lockfile first.');
const native = join(mobile, 'android');
const marker = join(native, '.todo-moe-generated.json');
if (existsSync(native) && !existsSync(marker)) throw new Error('Existing android/ is not marked as generated by Todo Moe. Preserve it and build in a fresh checkout; this script never deletes native work.');
const env = { ...process.env, APP_VARIANT: channel, MOE_VERSION_CODE: String(versionCode), MOE_SOURCE_SHA: sourceSha, EXPO_NO_TELEMETRY: '1', FOSS_BUILD: '1', CI: '1', NODE_ENV: 'production', GRADLE_USER_HOME: process.env.GRADLE_USER_HOME || join(root,'.tools/gradle-cache'), MINDWTR_ANDROID_ARCHS: option('--archs', 'arm64-v8a') };
if (!/^(arm64-v8a|armeabi-v7a|x86_64)(,(arm64-v8a|armeabi-v7a|x86_64))*$/.test(env.MINDWTR_ANDROID_ARCHS)) throw new Error('Invalid Android architecture list.');
run(bun, ['x', '--no-install', 'expo', 'prebuild', '--platform', 'android', '--no-install'], mobile, false, env);
writeFileSync(marker, JSON.stringify(report, null, 2) + '\n');
if (process.platform === 'win32') {
    const gradle = join(native, 'app/build.gradle');
    const source = readFileSync(gradle, 'utf8');
    const wrapper = '    cliFile = new File(projectRoot, "moe/brand/expo-cli.cjs")';
    if (!/^\s*cliFile\s*=.+$/m.test(source)) throw new Error('Missing Expo CLI Gradle entry; refusing an unverified Windows bundle command.');
    writeFileSync(gradle, source.replace(/^\s*cliFile\s*=.+$/m, wrapper));
}
if (channel === 'stable') {
    const gradle = join(native, 'app/build.gradle');
    const before = readFileSync(gradle, 'utf8');
    const after = before.replace(/(release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/, '$1signingConfig null');
    if (after === before && !/release\s*\{[\s\S]*?signingConfig null/.test(before)) throw new Error('Could not verify unsigned stable Gradle configuration.');
    writeFileSync(gradle, after);
} else {
    const gradle = join(native, 'app/build.gradle');
    writeFileSync(gradle, readFileSync(gradle, 'utf8').replace(/(release\s*\{[\s\S]*?)signingConfig null/, '$1signingConfig signingConfigs.debug'));
}
run(process.platform === 'win32' ? join(native, 'gradlew.bat') : join(native, 'gradlew'), [':app:assembleRelease', '--no-daemon', `-PreactNativeArchitectures=${env.MINDWTR_ANDROID_ARCHS}`], native, false, env);
const output = join(root, 'build/moe', `${channel}-${versionCode}-${sourceSha.slice(0, 12)}`);
mkdirSync(output, { recursive: true });
const config = JSON.parse(run(bun, ['x', '--no-install', 'expo', 'config', '--type', 'public', '--json'], mobile, true, env));
const apks = readdirSync(join(native, 'app/build/outputs/apk/release')).filter((name) => name.endsWith('.apk'));
if (!apks.length) throw new Error('Gradle produced no APK.');
const artifacts = apks.map((name) => {
    const targetName = `todo-moe-${config.version}-${channel}-vc${versionCode}-${name}`;
    const target = join(output, targetName);
    copyFileSync(join(native, 'app/build/outputs/apk/release', name), target);
    const contents = readFileSync(target);
    const sdkTools=join(sdk,'build-tools/36.0.0');
    const aapt=join(sdkTools,process.platform==='win32'?'aapt.exe':'aapt');
    const badging=run(aapt,['dump','badging',target],root,true);
    const pkg=badging.match(/^package: name='([^']+)' versionCode='(\d+)' versionName='([^']+)'/m);
    if(!pkg||pkg[1]!==config.android.package||Number(pkg[2])!==versionCode||pkg[3]!==config.version) throw new Error(`APK identity differs from requested build: ${targetName}`);
    let certificateSha256=null;
    if(channel==='development') {
        const signer=join(sdkTools,process.platform==='win32'?'apksigner.bat':'apksigner');
        const verified=run(signer,['verify','--print-certs',target],root,true);
        certificateSha256=verified.match(/Signer #1 certificate SHA-256 digest: ([a-f0-9]+)/i)?.[1]?.toLowerCase();
        if(!certificateSha256) throw new Error('Dev APK signing certificate was not verified.');
    }
    return { file: targetName, bytes: contents.length, sha256: createHash('sha256').update(contents).digest('hex'), certificateSha256 };
});
writeFileSync(join(output, 'build-manifest.json'), JSON.stringify({ ...report, ...config.extra.todoMoe, androidPackage: config.android.package, artifacts }, null, 2) + '\n');
writeFileSync(join(output, 'SHA256SUMS'), artifacts.map((item) => `${item.sha256}  ${item.file}`).join('\n') + '\n');
console.log(`Build artifacts: ${output}`);
